src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Fixes #9 
also added properties that will probably be required
Fixes # (issue)

fixed mapping iterator, added more properties

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Fix issue-23, lost non-default profile session

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_proxy.py

Release PR v1.0.5

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Related to: https://github.com/BstLabs/py-clvm/issues/98

Release PR v1.0.6

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py

mapping now ignores terminated instances

---

src/ec2instances/ec2_instance_mapping.py

Fixes #32 Add authentication callback. The first approach.

Add auth callback for all instances

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Fixes #35 Supply authentication callback globally

Issue-35, Supply authentication callback globally

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Pre-release PR v1.0.9b1

---

.vscode/settings.json
scripts/test-coverage.sh
scripts/type.sh
src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Pre-release PR v1.0.9b2

---

.github/workflows/changelog.yml
src/ec2instances/ec2_instance_proxy.py

Description:
- Defined a new method to support instance start/stop with a waiter
- Extra: Added changelog workflow
Fixes #41

Feat(general): Added support for `wait_until_running`

---

src/ec2instances/ec2_instance_proxy.py

Fixes #44  
Description:
- Modified execute for custom parameters through kwargs
- Reduced the default delay to 1

Feat(general): Modified execute for custom parameters and reduced default delay

---

src/ec2instances/ec2_instance_proxy.py

Fixes #46 
- unnecessary sleep time removed.
- return value that makes sense in a case 'wait' is off.
- an assertion for VM state.

Feat(general): Further enhancements for execute method

---

src/ec2instances/ec2_instance_proxy.py
test/test_remote_shell.py

Fix Ec2RemoteShellProxy.execute() args order (#51)

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_proxy.py
test/test_remote_shell.py

- reordered function arguments of execute()
- a new test for instance proxy

Release PR v1.0.11

---

src/ec2instances/ec2_instance_proxy.py

Fix issue 55: retry waiter.wait() with sleep(1)

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_proxy.py

Release PR v1.0.12

---

src/ec2instances/ec2_instance_proxy.py

fixed ec2 resouce not created from session

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_proxy.py

Release PR v1.0.13

---

src/ec2instances/ec2_instance_proxy.py

commands were being run as root and not ssm-user

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_proxy.py

Fixes in the command execution itself, all commands were being run as root, and some commands did not work. It didn't serve the purpose of SSM and prevented us from acting as human VM users.
Fixes #62  

Release PR v1.0.14

---

src/ec2instances/__init__.py
src/ec2instances/ec2_instance_mapping.py
src/ec2instances/ec2_instance_proxy.py

Release PR v1.0.15

---

src/ec2instances/ec2_instance_proxy.py
test/test_remote_shell.py

issue-72: fix Ec2RemoteShellProxy.execute() to run all commands as ssm-user
